Algoritmo "tabuada"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/30/2022
Var
// Seção de Declarações das variáveis
n, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um numero de 1 a 10: ")
   leia(n)
   i<- 1
   para i de 1 ate 10  faca
   escreval(n, " x ", i, " = ", n*i)
   fimpara
Fimalgoritmo