Algoritmo "imcSimples"

Var nome : caractere
peso, altura, imc: real
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      Escreval("Por favor, digite o seu nome")
      leia(nome)
      Escreval("Digite a sua altura")
      leia(altura)
      Escreval("Digite o seu peso")
      leia(peso)
      imc<- peso / (altura* 2)
      
      Escreval("IMC: ", imc)

Fimalgoritmo
